http:
  listener:
    host: "0.0.0.0"
    port: "8085"
  requester:
    travelOnTip:
      host: "0.0.0.0"
      port: "8083"
      routespath: "/TravelOnTip/routes"
      schedulespath: "/TravelOnTip/schedules"
    fastGo:
      host: "0.0.0.0"
      port: "8084"
      routespath: "/FastGo/routes"
      schedulespath: "/FastGo/schedules"